server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://192.168.129.109:3306/bss_dev?useUnicode=true&characterEncoding=utf8
    password: ambari
    username: ambari
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
